# Generated by Django 5.2.17 on 2026-09-16 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('OTHER', 'Other'), ('UNDISCLOSED', 'Undisclosed')], max_length=16)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=200)),
                ('insurance_provider', models.CharField(blank=True, max_length=160)),
                ('insurance_number', models.CharField(blank=True, max_length=80)),
                ('blood_group', models.CharField(blank=True, max_length=8)),
                ('allergies', models.TextField(blank=True)),
                ('medical_history', models.TextField(blank=True)),
                ('previous_medications', models.TextField(blank=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('specialization', models.CharField(max_length=120)),
                ('license_number', models.CharField(max_length=80, unique=True)),
                ('availability', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(default='ACTIVE', max_length=30)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='hospital.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nurse_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('license_number', models.CharField(max_length=80, unique=True)),
                ('shift', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(default='ACTIVE', max_length=30)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nurses', to='hospital.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='nurse_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
